-- Schema para staging de datos (H2 compatible)
-- JHOMERON Batch ETL - DEV mode

CREATE SCHEMA IF NOT EXISTS staging;

DROP TABLE IF EXISTS staging.pedidos;
CREATE TABLE staging.pedidos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente VARCHAR(150) NOT NULL,
    producto VARCHAR(150) NOT NULL,
    cantidad INTEGER NOT NULL,
    fecha_pedido DATE NOT NULL,
    fecha_carga TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    source VARCHAR(10) NOT NULL,
    lote VARCHAR(50),
    estado VARCHAR(20) DEFAULT 'PENDIENTE'
);

DROP TABLE IF EXISTS staging.ventas;
CREATE TABLE staging.ventas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_entry INTEGER NOT NULL,
    doc_line INTEGER NOT NULL,
    fecha DATE NOT NULL,
    codigo_cliente VARCHAR(50),
    cliente VARCHAR(255),
    departamento VARCHAR(100),
    provincia VARCHAR(100),
    distrito VARCHAR(100),
    codigo_vendedor INTEGER,
    vendedor VARCHAR(150),
    codigo_producto VARCHAR(50),
    producto VARCHAR(255),
    categoria VARCHAR(100),
    condicion_pago VARCHAR(100),
    cantidad NUMERIC(19, 4),
    precio_unitario NUMERIC(19, 4),
    base_imponible NUMERIC(19, 4),
    importe_total NUMERIC(19, 4),
    igv NUMERIC(19, 4),
    fecha_carga TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    source VARCHAR(20) DEFAULT 'SAP',
    lote VARCHAR(50),
    estado VARCHAR(20) DEFAULT 'PENDIENTE'
);
