-- Schema para staging de datos (H2 compatible)
-- JHOMERON Batch ETL - DEV mode

CREATE SCHEMA IF NOT EXISTS staging;

DROP TABLE IF EXISTS staging.pedidos;
CREATE TABLE staging.pedidos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente VARCHAR(150) NOT NULL,
    producto VARCHAR(150) NOT NULL,
    cantidad INTEGER NOT NULL,
    fecha_pedido DATE NOT NULL,
    fecha_carga TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    source VARCHAR(10) NOT NULL,
    lote VARCHAR(50),
    estado VARCHAR(20) DEFAULT 'PENDIENTE'
);
